### ISSUE TITLE
Please check the deployment webhook to make the trigger work again

### ISSUE THREAD

**Issue by myloft** [zhuangbiaowei/learn-with-open-source#44]
Hi!
It seems that our commits on GitHub can not trigger builds on GitBook and the last update is 4 years ago. Maybe you could check the deployment webhook by reading [GitHub Integration | GitBook.com Documentation](https://gitbookio.gitbooks.io/documentation/github/index.html).
![Update time](https://user-images.githubusercontent.com/25258169/67146248-d81b8880-f2bb-11e9-9a9f-7e4cf1deb4ea.png)

**Comment by zhuangbiaowei** [comment]
已经配置完成，并修改了README文件
