### ISSUE TITLE
怎样练习一万小时

### ISSUE THREAD

**Issue by secbro** [zhuangbiaowei/learn-with-open-source#9]
在您贴出的文章链接中，“刻意训练”不仅仅是重复练习，更重要的是“做自己不擅长的事情”。所以我觉得直接否定“一万小时训练法”是不科学的。

**Comment by FrankBian** [comment]
训练一万小时，应该等同于 重复到养成这个习惯 或者 已经彻底掌握 ，至于是多长时间 ，应该是随便。
