### ISSUE TITLE
配置Github Actions，自动化发布编译完成的PDF格式

### ISSUE THREAD

**Issue by zhuangbiaowei** [zhuangbiaowei/learn-with-open-source#93]

**Comment by zhuangbiaowei** [comment]
有两个选择，一个是建立一个release分支。另一个是由新建tag的时间触发。

我推荐后一种。

**Comment by myloft** [comment]
#121

**Comment by myloft** [comment]
目前自动构建是由 v* 标签触发，会自动创建 release 并上传附件。自动发布的默认标题 Release: {tag}，可以手动修改。如果手动发布 release 会导致流程中的创建 release 过程发生冲突，导致无法上传附件。

**Comment by zhuangbiaowei** [comment]
理解了，我回头手工推送一个tag测试下。

**Comment by myloft** [comment]
以下是我测试的流程

1. 打标签
```shell
git tag -a v0.9 -m "借助开源学习开发，0.9版发布"
git push origin --tag
```

2. 自动化构建并创建 Draft Release
![自动化构建](https://user-images.githubusercontent.com/25258169/67262010-bf86ba80-f4d5-11e9-9349-3c51a987ddfb.png)

3. 修改 Draft 并发布
![修改 Draft](https://user-images.githubusercontent.com/25258169/67262133-3ae86c00-f4d6-11e9-8134-0aa45972478f.png)
![发布 Release](https://user-images.githubusercontent.com/25258169/67262272-c3670c80-f4d6-11e9-9f9f-79209b2c5e37.png)

**Comment by zhuangbiaowei** [comment]
测试通过，非常棒，本issue关闭！
